#!/usr/bin/env python3
"""
Readonly baseline scanner for refactor checkpoints.
Generates BASELINE_SNAPSHOT.md from static contracts in the repo.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
INO = ROOT / "control_statie_v41_MOD_TDA7439_copy_20260216001243.ino"
PY_FILES = [
    ROOT / "raspberry_moode_bridge.py",
    ROOT / "raspberry_volumio_bridge.py",
    ROOT / "windows_foobar_bridge.py",
]
OUT = ROOT / "BASELINE_SNAPSHOT.md"


def scan_routes(text: str) -> list[str]:
    pat = re.compile(r'server\.on\("([^"]+)"')
    seen = []
    for m in pat.finditer(text):
        p = m.group(1)
        if p not in seen:
            seen.append(p)
    return seen


def scan_protocol_markers(py_text: str) -> list[str]:
    markers = []
    for token in ("CMD|", "GET", "STAT|", "/state", "/cmd?c="):
        if token in py_text:
            markers.append(token)
    return markers


def main() -> int:
    ino_text = INO.read_text(encoding="utf-8", errors="ignore")
    routes = scan_routes(ino_text)

    lines = []
    lines.append("# Baseline Snapshot")
    lines.append("")
    lines.append("Generated by `baseline_scan.py` for aggressive refactor checkpoints.")
    lines.append("")
    lines.append("## Web Routes (from .ino)")
    for r in routes:
        lines.append(f"- `{r}`")
    lines.append("")
    lines.append("## Bridge Protocol Markers")
    for pyf in PY_FILES:
        txt = pyf.read_text(encoding="utf-8", errors="ignore")
        marks = scan_protocol_markers(txt)
        lines.append(f"- `{pyf.name}`: {', '.join(f'`{m}`' for m in marks) if marks else 'none'}")
    lines.append("")
    lines.append("## Compatibility Notes")
    lines.append("- Keep route names and `/status` payload field names stable through Phase 2-4.")
    lines.append("- Keep UART line format `STAT|state|title|artist|extra` stable through Python refactor.")
    lines.append("- Keep foobar bridge endpoints `/state` and `/cmd?c=...` stable.")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote: {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

